# https://docs.github.com/en/actions/guides
# CI name , it will display on github's action page menu
name: Build Python+Firefox Image
# trigger on which this CI should be run
on: # push operation is operate
  push:
    # here since my repository branch is named `main` , you should follow your own repository like `master`
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
# CI enviroment settings
env:
  TAG_NAME: "pythonfirefox"
jobs:
  build:
    name: 构建,发布
    runs-on: ubuntu-latest # use latest ubuntu to run the job
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    strategy:
      matrix:
        python_version: ["3.6", "3.6.15", "3.7", "3.7.16", "3.8", "3.8.16", "3.9", "3.9.16", "3.10" , "3.10.9","3.11","3.11.2"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      # here are some step followed , each step must have `uses` or `run` key , for CI to run
      # other key like `name`,`with`,`env` is optional
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Get latest version
        run: |
          python -m pip install requests
          python latest_version_firefox.py
      - name: Output Docker info
        run: docker info
      - name: Sets build date
        run: echo "BUILD_DATE=$(date '+%Y%m%d')" >> $GITHUB_ENV
      - name: tail from FIREFOX_ESR_VERSION to GITHUB_ENV
        run: tail ./FIREFOX_ESR_VERSION >> $GITHUB_ENV
      - name: set tag GECKODRIVER_VERSION version
        run: tail ./GECKODRIVER_VERSION >> $GITHUB_ENV
      
      - name: check firefox_version
        run:  |
          echo ${{env.FIREFOX_ESR_VERSION}}
      - name: check geckodriver
        run:  |
          echo ${{env.GECKODRIVER_VERSION}}
      - name: check python_version
        run:  |
          echo ${{matrix.python_version}}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #版本号第一位不允许空格 https://github.com/docker/build-push-action
      - name: Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          #构造环境变量传入list https://github.com/docker/build-push-action
          build-args: |
            PYTHON_VERSION=${{matrix.python_version}}
            FIREFOX_ESR_VERSION=${{env.FIREFOX_ESR_VERSION}}
            GECKODRIVER_VERSION=${{env.GECKODRIVER_VERSION}}
          # tag 不允许出现-
          tags: "includeno/${{ env.TAG_NAME }}:${{matrix.python_version}}.latest,includeno/${{ env.TAG_NAME }}:${{matrix.python_version}}.firefox${{env.FIREFOX_ESR_VERSION}}"
          push: true
      - name: The job has succeeded
        if: ${{ success() }}
        run: echo "success"
    
   